version: '3.9'

services:
  postgres:
    image: postgres:16

    container_name: nest-postgres

    restart: always

    ports:
      - '5434:5432'

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestdb

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
